### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{

  "username": "omar",
  "password": "1245adassdsad",
  "email": "test45@test.com",
  "role": "STUDENT"
}